name: Build and Publish to PyPI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install tomli for python before 3.11
        run: python -m pip install tomli
      - name: Verify Version Match
        run: |
          VERSION=$(python -c "import tomli; print(tomli.load('pyproject.toml')['project']['version'])")
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "extracted version from setup.py: $VERSION"
          echo "Git tag is: $TAG_NAME"
          if [ "v$VERSION" != "$TAG_NAME" ]; then
            echo "Error: VERSION file does not match the git tag."
            exit 1
          fi

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Publish package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*

